[package]
name = "tafl-egui"
version = "0.1.0"
edition = "2021"

[dependencies]
hnefatafl = { path = "../hnefatafl" }
rand = {  version = "0.8.5", features = ["small_rng"] }
egui = "0.29.1"
eframe = "0.29.1"
egui_extras = {  version = "0.29.1", features = ["file", "svg"] }
